import grayHouse from '@/../public/images/beautiful-house.png';

export const BuyPropertyData = [
  {
    id: 1,
    category: 'buy',
    thumbnail: grayHouse.src,
    title: 'the city card',
    location: '1011 Robson Street, Vancouver, BC V6E 1C2',
    price: '$ 8000',
    status: 'buy',
    bathrooms: '6 bathrooms',
    bedrooms: '5 bedrooms',
    area: '700 SQ.YD',
  },
  {
    id: 2,
    category: 'buy',
    thumbnail: grayHouse.src,
    title: 'the city card',
    location: '1011 Robson Street, Vancouver, BC V6E 1C2',
    price: '$ 8000',
    status: 'buy',
    bathrooms: '6 bathrooms',
    bedrooms: '5 bedrooms',
    area: '700 SQ.YD',
  },
  {
    id: 3,
    category: 'buy',
    thumbnail: grayHouse.src,
    title: 'the city card',
    location: '1011 Robson Street, Vancouver, BC V6E 1C2',
    price: '$ 8000',
    status: 'buy',
    bathrooms: '6 bathrooms',
    bedrooms: '5 bedrooms',
    area: '700 SQ.YD',
  },
  {
    id: 4,
    category: 'buy',
    thumbnail: grayHouse.src,
    title: 'the city card',
    location: '1011 Robson Street, Vancouver, BC V6E 1C2',
    price: '$ 8000',
    status: 'buy',
    bathrooms: '6 bathrooms',
    bedrooms: '5 bedrooms',
    area: '700 SQ.YD',
  },
  {
    id: 5,
    category: 'buy',
    thumbnail: grayHouse.src,
    title: 'the city card',
    location: '1011 Robson Street, Vancouver, BC V6E 1C2',
    price: '$ 8000',
    status: 'buy',
    bathrooms: '6 bathrooms',
    bedrooms: '5 bedrooms',
    area: '700 SQ.YD',
  },
  {
    id: 6,
    category: 'buy',
    thumbnail: grayHouse.src,
    title: 'the city card',
    location: '1011 Robson Street, Vancouver, BC V6E 1C2',
    price: '$ 8000',
    status: 'buy',
    bathrooms: ' 6 bathrooms',
    bedrooms: '5 bedrooms',
    area: '700 SQ.YD',
  },
  {
    id: 7,
    category: 'buy',
    thumbnail: grayHouse.src,
    title: 'the city card',
    location: '1011 Robson Street, Vancouver, BC V6E 1C2',
    price: '$ 8000',
    status: 'buy',
    bathrooms: ' 6 bathrooms',
    bedrooms: '5 bedrooms',
    area: '700 SQ.YD',
  },
];
