import house from '@/../public/images/card-house.png';

export const ProductCardHorizontalData = [
  {
    thumbnail: house.src,
    washRoom: 'https://placehold.co/600x600/png',
    tvLaunch: 'https://placehold.co/600x600/png',
    lounge: 'https://placehold.co/600x600/png',
    kitchen: 'https://placehold.co/600x600/png',
    title: 'Arabian Villas',
    location: '1213 Rue Papineau, Montreal, QC H2L 3B5',
    price: '$ 1,050',
    beds: '8 BedRooms',
    bath: '8 BathRooms',
    square: '400 SQ.YD',
    rate: '4.8',
  },
  {
    thumbnail: house.src,
    washRoom: 'https://placehold.co/600x600/png',
    tvLaunch: 'https://placehold.co/600x600/png',
    lounge: 'https://placehold.co/600x600/png',
    kitchen: 'https://placehold.co/600x600/png',
    location: '1213 Rue Papineau, Montreal, QC H2L 3B5',
    title: 'Arabian Villas 1',
    price: '$ 1,050',
    beds: '8 BedRooms',
    bath: '8 BathRooms',
    square: '400 SQ.YD',
    rate: '4.8',
  },
  {
    thumbnail: house.src,
    washRoom: 'https://placehold.co/600x600/png',
    tvLaunch: 'https://placehold.co/600x600/png',
    lounge: 'https://placehold.co/600x600/png',
    kitchen: 'https://placehold.co/600x600/png',
    location: '1213 Rue Papineau, Montreal, QC H2L 3B5',
    title: 'Arabian house 2',
    price: '$ 1,050',
    beds: '5 BedRooms',
    bath: '9 BathRooms',
    square: '550 SQ.YD',
    rate: '6.8',
  },
  {
    thumbnail: house.src,
    washRoom: 'https://placehold.co/600x600/png',
    tvLaunch: 'https://placehold.co/600x600/png',
    lounge: 'https://placehold.co/600x600/png',
    kitchen: 'https://placehold.co/600x600/png',
    location: '1213 Rue Papineau, Montreal, QC H2L 3B5',
    title: 'Arabian Villas 3',
    price: '$ 1,050',
    beds: '8 BedRooms',
    bath: '8 BathRooms',
    square: '400 SQ.YD',
    rate: '4.8',
  },
  {
    thumbnail: house.src,
    washRoom: 'https://placehold.co/600x600/png',
    tvLaunch: 'https://placehold.co/600x600/png',
    lounge: 'https://placehold.co/600x600/png',
    kitchen: 'https://placehold.co/600x600/png',
    location: '1213 Rue Papineau, Montreal, QC H2L 3B5',
    title: 'Arabian Villas 4',
    price: '$ 1,050',
    beds: '8 BedRooms',
    bath: '8 BathRooms',
    square: '400 SQ.YD',
    rate: '4.8',
  },
  {
    thumbnail: house.src,
    washRoom: 'https://placehold.co/600x600/png',
    tvLaunch: 'https://placehold.co/600x600/png',
    lounge: 'https://placehold.co/600x600/png',
    kitchen: 'https://placehold.co/600x600/png',
    location: '1213 Rue Papineau, Montreal, QC H2L 3B5',
    title: 'Arabian Villas 5',
    price: '$ 1,050',
    beds: '8 BedRooms',
    bath: '8 BathRooms',
    square: '400 SQ.YD',
    rate: '4.8',
  },
  {
    thumbnail: house.src,
    washRoom: 'https://placehold.co/600x600/png',
    tvLaunch: 'https://placehold.co/600x600/png',
    lounge: 'https://placehold.co/600x600/png',
    kitchen: 'https://placehold.co/600x600/png',
    location: '1213 Rue Papineau, Montreal, QC H2L 3B5',
    title: 'Arabian Villas 6',
    price: '$ 1,050',
    beds: '8 BedRooms',
    bath: '8 BathRooms',
    square: '400 SQ.YD',
    rate: '4.8',
  },
];
