import grayHouse from '@/../public/icons/grayHouse.svg';
import grayHous from '@/../public/images/beautifulHouse.png';

export const CardsData = [
  {
    id: 1,
    category: 'buy',
    icon: { grayHous },
    title: 'the city card',
    location: '1011 Robson Street, Vancouver, BC V6E 1C2',
    thumbnail: '/mouth',
    price: '$ 8000',
    statusChip: 'rent',
    bathrooms: ' 6 bathrooms',
    bedrooms: '5 bedrooms',
    area: '700 SQ.YD',
  },
  {
    id: 2,
    category: 'buy',
    icon: { grayHouse },
    title: 'the city card',
    location: '1011 Robson Street, Vancouver, BC V6E 1C2',
    thumbnail: '/mouth',
    price: '$ 8000',
    statusChip: 'rent',
    bathrooms: ' 6 bathrooms',
    bedrooms: '5 bedrooms',
    area: '700 SQ.YD',
  },
  {
    id: 3,
    category: 'buy',
    icon: { grayHouse },
    title: 'the city card',
    location: '1011 Robson Street, Vancouver, BC V6E 1C2',
    thumbnail: '/mouth',
    price: '$ 8000',
    statusChip: 'rent',
    bathrooms: ' 6 bathrooms',
    bedrooms: '5 bedrooms',
    area: '700 SQ.YD',
  },
  {
    id: 4,
    category: 'buy',
    icon: { grayHouse },
    title: 'the city card',
    location: '1011 Robson Street, Vancouver, BC V6E 1C2',
    thumbnail: '/mouth',
    price: '$ 8000',
    statusChip: 'rent',
    bathrooms: ' 6 bathrooms',
    bedrooms: '5 bedrooms',
    area: '700 SQ.YD',
  },
  {
    id: 5,
    category: 'buy',
    icon: { grayHouse },
    title: 'the city card',
    location: '1011 Robson Street, Vancouver, BC V6E 1C2',
    thumbnail: '/mouth',
    price: '$ 8000',
    statusChip: 'rent',
    bathrooms: ' 6 bathrooms',
    bedrooms: '5 bedrooms',
    area: '700 SQ.YD',
  },
  {
    id: 6,
    category: 'buy',
    icon: { grayHouse },
    title: 'the city card',
    location: '1011 Robson Street, Vancouver, BC V6E 1C2',
    thumbnail: '/mouth',
    price: '$ 8000',
    statusChip: 'rent',
    bathrooms: ' 6 bathrooms',
    bedrooms: '5 bedrooms',
    area: '700 SQ.YD',
  },
  {
    id: 7,
    category: 'buy',
    icon: { grayHouse },
    title: 'the city card',
    location: '1011 Robson Street, Vancouver, BC V6E 1C2',
    thumbnail: '/mouth',
    price: '$ 8000',
    statusChip: 'rent',
    bathrooms: ' 6 bathrooms',
    bedrooms: '5 bedrooms',
    area: '700 SQ.YD',
  },
];
