// src/constant/cards/rent-buy-property-data.ts

// Image Import
import grayHouse from '@/../public/images/beautiful-house.png';

// ============================== RentPropertyData =============================
export const RentPropertyData = [
  {
    _id: '1',
    purpose: 'rent',
    thumbnail: grayHouse.src,
    name: 'The City Card',
    city: 'karachi',
    country: 'Pakistan',
    price: 8000,
    bathrooms: 6,
    bedrooms: 5,
    area: '700 SQ.YD',
  },
  {
    _id: '2',
    purpose: 'rent',
    thumbnail: grayHouse.src,
    name: 'The City Card',
    city: 'karachi',
    country: 'Pakistan',
    price: 8000,
    bathrooms: 6,
    bedrooms: 5,
    area: '700 SQ.YD',
  },
  {
    _id: '3',
    purpose: 'rent',
    thumbnail: grayHouse.src,
    name: 'The City Card',
    city: 'karachi',
    country: 'Pakistan',
    price: 8000,
    bathrooms: 6,
    bedrooms: 5,
    area: '700 SQ.YD',
  },
  {
    _id: '4',
    purpose: 'rent',
    thumbnail: grayHouse.src,
    name: 'The City Card',
    city: 'karachi',
    country: 'Pakistan',
    price: 8000,
    bathrooms: 6,
    bedrooms: 5,
    area: '700 SQ.YD',
  },
  {
    _id: '5',
    purpose: 'rent',
    thumbnail: grayHouse.src,
    name: 'The City Card',
    city: 'karachi',
    country: 'Pakistan',
    price: 8000,
    bathrooms: 6,
    bedrooms: 5,
    area: '700 SQ.YD',
  },
  {
    _id: '6',
    purpose: 'rent',
    thumbnail: grayHouse.src,
    name: 'The City Card',
    city: 'karachi',
    country: 'Pakistan',
    price: 8000,
    bathrooms: 6,
    bedrooms: 5,
    area: '700 SQ.YD',
  },
  {
    _id: '7',
    purpose: 'rent',
    thumbnail: grayHouse.src,
    name: 'The City Card',
    city: 'karachi',
    country: 'Pakistan',
    price: 8000,
    bathrooms: 6,
    bedrooms: 5,
    area: '700 SQ.YD',
  },
];

// ============================== RentPropertyData =============================
export const BuyPropertyData = [
  {
    _id: '1',
    purpose: 'buy',
    thumbnail: grayHouse.src,
    name: 'The City Card',
    city: 'karachi',
    country: 'Pakistan',
    price: 8000,
    bathrooms: 6,
    bedrooms: 5,
    area: '700 SQ.YD',
  },
  {
    _id: '2',
    purpose: 'buy',
    thumbnail: grayHouse.src,
    name: 'The City Card',
    city: 'karachi',
    country: 'Pakistan',
    price: 8000,
    bathrooms: 6,
    bedrooms: 5,
    area: '700 SQ.YD',
  },
  {
    _id: '3',
    purpose: 'buy',
    thumbnail: grayHouse.src,
    name: 'The City Card',
    city: 'karachi',
    country: 'Pakistan',
    price: 8000,
    bathrooms: 6,
    bedrooms: 5,
    area: '700 SQ.YD',
  },
  {
    _id: '4',
    purpose: 'buy',
    thumbnail: grayHouse.src,
    name: 'The City Card',
    city: 'karachi',
    country: 'Pakistan',
    price: 8000,
    bathrooms: 5,
    bedrooms: 5,
    area: '700 SQ.YD',
  },
  {
    _id: '5',
    purpose: 'buy',
    thumbnail: grayHouse.src,
    name: 'The City Card',
    city: 'karachi',
    country: 'Pakistan',
    price: 8000,
    bathrooms: 5,
    bedrooms: 5,
    area: '700 SQ.YD',
  },
  {
    _id: '6',
    purpose: 'buy',
    thumbnail: grayHouse.src,
    name: 'The City Card',
    city: 'karachi',
    country: 'Pakistan',
    price: 8000,
    bathrooms: 6,
    bedrooms: 5,
    area: '700 SQ.YD',
  },
  {
    _id: '7',
    purpose: 'buy',
    thumbnail: grayHouse.src,
    name: 'The City Card',
    city: 'karachi',
    country: 'Pakistan',
    price: 8000,
    bathrooms: 6,
    bedrooms: 5,
    area: '700 SQ.YD',
  },
];
