import Navbar from '@/components/layouts/navbar';
import type { Metadata } from 'next';
import './globals.css';
import Footer from '@/components/layouts/footer';

export const metadata: Metadata = {
  title: 'Key Vista',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang='en'
      suppressHydrationWarning
    >
      <body className={``}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
