// src/app/layout.tsx
// Import Next
import type { Metadata } from 'next';

// Import global.css
import './globals.css';

export const metadata: Metadata = {
  title: 'Key Vista',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`antialiased`}
        suppressHydrationWarning
      >
        {children}
      </body>
    </html>
  );
}
