import Providers from '@/providers';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

// Import global.css
import './globals.css';

export const metadata: Metadata = {
  title: 'Key Vista',
  description: 'Generated by create next app',
};
const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`antialiased scroll-smooth ${inter.className} `}
        suppressHydrationWarning
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
