export const chatHeads = [
  {
    id: 1,
    name: 'Emma Thompson',
    message: 'Hello, how are you?',
    time: '10:00 AM',
    image: '/navbar/profile.svg',
  },
  {
    id: 2,
    name: 'James Wilson',
    message:
      'Hello, how are you? Lorem ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit, quis!',
    time: '10:00 AM',
    image: '/navbar/profile.svg',
  },
  {
    id: 3,
    name: 'Muhammad Mursaleen Ansari',
    message: 'Hello, how are you?',
    time: '10:00 AM',
    image: '/navbar/profile.svg',
  },
  {
    id: 4,
    name: 'Michael Brown',
    message:
      'Hello, how are you? Lorem ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit, quis!',
    time: '10:00 AM',
    image: '/navbar/profile.svg',
  },
  {
    id: 5,
    name: 'Isabella Garcia dolor sit amet consectetur adipisicing elit. Reprehenderit, quis!',
    message: 'Hello, how are you?',
    time: '10:00 AM',
    image: '/navbar/profile.svg',
  },

  {
    id: 6,
    name: 'William Taylor',
    message: 'Hello, how are you?',
    time: '10:00 AM',
    image: '/navbar/profile.svg',
  },
  {
    id: 7,
    name: 'Olivia Martinez',
    message: 'Hello, how are you?',
    time: '10:00 AM',
    image: '/navbar/profile.svg',
  },
  {
    id: 8,
    name: 'Ethan Anderson',
    message: 'Hello, how are you?',
    time: '10:00 AM',
    image: '/navbar/profile.svg',
  },
  {
    id: 9,
    name: 'Ava Johnson',
    message: 'Hello, how are you?',
    time: '10:00 AM',
    image: '/navbar/profile.svg',
  },
  {
    id: 10,
    name: 'Noah Davis',
    message: 'Hello, how are you?',
    time: '10:00 AM',
    image: '/navbar/profile.svg',
  },
  {
    id: 11,
    name: 'Mia Rodriguez',
    message: 'Hello, how are you?',
    time: '10:00 AM',
    image: '/navbar/profile.svg',
  },
  {
    id: 12,
    name: 'Lucas White',
    message: 'Hello, how are you?',
    time: '10:00 AM',
    image: '/navbar/profile.svg',
  },
  {
    id: 13,
    name: 'Charlotte Lee',
    message: 'Hello, how are you?',
    time: '10:00 AM',
    image: '/navbar/profile.svg',
  },
  {
    id: 14,
    name: 'Alexander King',
    message: 'Hello, how are you?',
    time: '10:00 AM',
    image: '/navbar/profile.svg',
  },
  {
    id: 15,
    name: 'Amelia Wright',
    message: 'Hello, how are you?',
    time: '10:00 AM',
    image: '/navbar/profile.svg',
  },
  {
    id: 16,
    name: 'Benjamin Scott',
    message: 'Hello, how are you?',
    time: '10:00 AM',
    image: '/navbar/profile.svg',
  },
];
